- name: create poolctl dir
  file:
    path: /opt/poolctl
    state: directory
    recurse: yes

- name: archive sanic-be
  delegate_to: localhost
  run_once: yes
  archive:
    path: ../../../sanic-be
    dest: /tmp/sanic-be.gz

- name: upload and extract sanic-be.gz
  unarchive:
    src: /tmp/sanic-be.gz
    dest: /opt/poolctl

- name: prepare custom virtualenv executable
  template:
    src: virtualenv-custom.j2
    dest: /usr/local/bin/virtualenv-custom
    mode: 0775

- name: create virtualenv, update pip and setuptools
  pip:
    virtualenv: "{{ pyvenv_home }}"
    virtualenv_command: virtualenv-custom
    name:
      - pip
      - setuptools
    state: latest

- name: make sure wheel is not present
  pip:
    virtualenv: "{{ pyvenv_home }}"
    name:
      - wheel
    state: absent

- name: install requirements in the virtualenv
  pip:
    virtualenv: "{{ pyvenv_home }}"
    requirements: /opt/poolctl/sanic-be/requirements/req-runtime.txt

- name: set environment name variable creation
  template:
    src: poolctl.sh.j2
    dest: /etc/profile.d/poolctl.sh
  notify: reboot

- name: create sanic systemd script
  template:
    src: poolctl-be.service.j2
    dest: /lib/systemd/system/poolctl-restapi.service

- name: enable and start poolctl-restapi service
  systemd:
    name: poolctl-restapi
    state: restarted
    enabled: yes
    daemon_reload: yes
