- name: create webroot and static dirs
  file:
    path: /opt/poolctl/webroot/static
    state: directory
    recurse: yes

- name: ensure webapp is built
  delegate_to: localhost
  run_once: yes
  command: ionic build --engine=browser --prod
  args:
    chdir: ../../../ionic-fe
    creates: ../../../ionic-fe/www

- name: archive www
  delegate_to: localhost
  run_once: yes
  archive:
    path: ../../../ionic-fe/www
    dest: /tmp/www.gz

- name: upload and extract www.gz
  unarchive:
    src: /tmp/www.gz
    dest: /opt/poolctl/webroot
