---
#: Setup dedicated poolctl user + group and lock down pi user for security

- name: create group rudy
  group:
    name: rudy
    system: yes

- name: create user rudy
  user:
    name: rudy
    password: '{{ defaut_pass }}'
    update_password: on_create
    shell: /bin/bash
    group: rudy
    groups:
      - adm
      - dialout
      - cdrom
      - sudo
      - audio
      - video
      - plugdev
      - games
      - users
      - input
      - netdev
      - spi
      - i2c
      - gpio

- name: setup passwordless sudo for rudy
  copy:
    content: "rudy ALL=(ALL) NOPASSWD: ALL\n"
    dest: /etc/sudoers.d/020_rudy-nopasswd
    mode: 0440

- name: lock down user pi
  user:
    name: pi
    # password: '*' disables user - linux-specific
    password: '*'
    shell: /bin/false

#- name: lock down user root
#  user:
#    name: root
#    password: '*'  # disable user - linux-specific
