---
#: Lock down pi user (and potentially root) for improved security

- name: Create group rudy
  group:
    name: rudy
    system: yes


- name: Create user rudy
  user:
    name: rudy
    password: '{{ defaut_pass }}'
    update_password: on_create
    shell: /bin/bash
    group: rudy
    groups:
      - adm
      - dialout
      - cdrom
      - sudo
      - audio
      - video
      - plugdev
      - games
      - users
      - input
      - netdev
      - spi
      - i2c
      - gpio


- name: Setup passwordless sudo for rudy
  copy:
    content: "rudy ALL=(ALL) NOPASSWD: ALL\n"
    dest: /etc/sudoers.d/020_rudy-nopasswd
    mode: 0440


- name: Lock down user pi
  user:
    name: pi
    password: '*'  # disable user - linux-specific
    shell: /bin/false


- name: Lock down user root
  user:
    name: root
    password: '*'  # disable user - linux-specific
