- name: system configurations
  include: system.yml

- name: backend configurations
  include: backend.yml

- name: frontend configurations
  include: frontend.yml

- name: nginx configurations
  include: nginx.yml
