---
#: nginx setup

- name: Install nginx package
  apt:
    name: nginx
    state: latest


- name: Setup nginx default host config
  template:
    # src: nginx-default.j2  # TODO: revisit
    src: nginx-poolctl.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
  vars:
    site_hostname: _


- name: Enable nginx default site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: restart nginx


- name: Setup nginx poolctl site config
  template:
    src: nginx-poolctl.j2
    dest: /etc/nginx/sites-available/poolctl
  notify: restart nginx
  vars:
    site_hostname: '{{ nginx_hostname }}'


- name: Enable nginx poolctl site
  file:
    src: /etc/nginx/sites-available/poolctl
    dest: /etc/nginx/sites-enabled/poolctl
    state: link
  notify: restart nginx
