- name: set proper timezone
  timezone:
    name: '{{ timezone }}'

# This one should be a part of a baseline setup
#- name: apt full upgrade
#  apt:
#    update_cache: yes
#    upgrade: full

- name: apt update and install pigpiod
  apt:
    name:
      - python3.7
      - python3-distutils
      - python3.7-venv
      - python3-pip
      - python3.7-dev
      - nginx
    state: latest

- name: install pigpiod and tools
  apt:
    name:
      # pigpio-tools not strictly necessary but might help during troubleshooting
      - pigpio-tools
      - pigpiod
    state: latest
  notify: restart pigpiod

- name: tune pgpiod startup arguments
  lineinfile:
    path: /lib/systemd/system/pigpiod.service
    regexp: '^\s*ExecStart\s*='
    line: ExecStart=/usr/bin/pigpiod -s 10 -b 200 -f
  notify: restart pigpiod

- name: create system group _poolctl
  group:
    name: '{{ poolctl_group }}'
    system: yes

- name: create system user _poolctl
  user:
    name: '{{ poolctl_user }}'
    system: yes
    home: '{{ poolctl_home }}'
    shell: /bin/false
    group: '{{ poolctl_group }}'
    groups:
      - spi
      - i2c
      - gpio
