#: Default variables. (Override in vars/main.yml.)

#: Server (=pool) time zone. This is important! RPis usually come
#: with Europe/London default setup which creates problems ;)
timezone: Europe/Sofia

#: The env name considered by the REST API back-end (sanic-be)
environment_name: stage  # integration, stage, prod (also local if necessary)

#: The poolctl system userm group and home directory
poolctl_user: _poolctl
poolctl_group: _poolctl
poolctl_home: /opt/poolctl

#: Location for the python venv for the back-end
pyvenv_home: '{{ poolctl_home }}/venv'

#: poolctl apps distribution home
dist_home: '{{ poolctl_home }}/dist'

#: default password to be set
defaut_pass: $6$UiwEdWg2IzXeWSwF$AWz/ZiUoLXXplgjyZ.coECvyFxLOx6JMu5DB7emjICGVwpuOsYwtZLYzprlWLEso.x9sOmZHkP.0RvtJsQVh./
